language: c++

os:
  - linux

dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: "ppa:beineri/opt-qt-5.14.1-bionic"
    packages:
      - qt514-meta-minimal
      - mesa-common-dev
      - libglu1-mesa-dev


script:
  - export CC=gcc-7
  - export CXX=g++-7
  - mkdir build
  - cd build
  - source /opt/qt514/bin/qt514-env.sh
  - cmake ../. -DCMAKE_PREFIX_PATH="/opt/qt514/lib/cmake"
  - make
  - ls ../bin
  - ../bin/SVMT